# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wyzlic_a/blih/cpp/jason

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wyzlic_a/blih/cpp/jason

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wyzlic_a/blih/cpp/jason/CMakeFiles /home/wyzlic_a/blih/cpp/jason/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wyzlic_a/blih/cpp/jason/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testsOS

# Build rule for target.
testsOS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testsOS
.PHONY : testsOS

# fast build rule for target.
testsOS/fast:
	$(MAKE) -f CMakeFiles/testsOS.dir/build.make CMakeFiles/testsOS.dir/build
.PHONY : testsOS/fast

#=============================================================================
# Target rules for targets named testsCPU_FREQ

# Build rule for target.
testsCPU_FREQ: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testsCPU_FREQ
.PHONY : testsCPU_FREQ

# fast build rule for target.
testsCPU_FREQ/fast:
	$(MAKE) -f CMakeFiles/testsCPU_FREQ.dir/build.make CMakeFiles/testsCPU_FREQ.dir/build
.PHONY : testsCPU_FREQ/fast

#=============================================================================
# Target rules for targets named EntropyInfo

# Build rule for target.
EntropyInfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EntropyInfo
.PHONY : EntropyInfo

# fast build rule for target.
EntropyInfo/fast:
	$(MAKE) -f CMakeFiles/EntropyInfo.dir/build.make CMakeFiles/EntropyInfo.dir/build
.PHONY : EntropyInfo/fast

#=============================================================================
# Target rules for targets named SysinfoModule

# Build rule for target.
SysinfoModule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SysinfoModule
.PHONY : SysinfoModule

# fast build rule for target.
SysinfoModule/fast:
	$(MAKE) -f CMakeFiles/SysinfoModule.dir/build.make CMakeFiles/SysinfoModule.dir/build
.PHONY : SysinfoModule/fast

#=============================================================================
# Target rules for targets named testsNETWORK

# Build rule for target.
testsNETWORK: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testsNETWORK
.PHONY : testsNETWORK

# fast build rule for target.
testsNETWORK/fast:
	$(MAKE) -f CMakeFiles/testsNETWORK.dir/build.make CMakeFiles/testsNETWORK.dir/build
.PHONY : testsNETWORK/fast

#=============================================================================
# Target rules for targets named cpp_gkrellm

# Build rule for target.
cpp_gkrellm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_gkrellm
.PHONY : cpp_gkrellm

# fast build rule for target.
cpp_gkrellm/fast:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/build
.PHONY : cpp_gkrellm/fast

#=============================================================================
# Target rules for targets named testsDate

# Build rule for target.
testsDate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testsDate
.PHONY : testsDate

# fast build rule for target.
testsDate/fast:
	$(MAKE) -f CMakeFiles/testsDate.dir/build.make CMakeFiles/testsDate.dir/build
.PHONY : testsDate/fast

#=============================================================================
# Target rules for targets named UserInfo

# Build rule for target.
UserInfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UserInfo
.PHONY : UserInfo

# fast build rule for target.
UserInfo/fast:
	$(MAKE) -f CMakeFiles/UserInfo.dir/build.make CMakeFiles/UserInfo.dir/build
.PHONY : UserInfo/fast

#=============================================================================
# Target rules for targets named NetworkInfo

# Build rule for target.
NetworkInfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NetworkInfo
.PHONY : NetworkInfo

# fast build rule for target.
NetworkInfo/fast:
	$(MAKE) -f CMakeFiles/NetworkInfo.dir/build.make CMakeFiles/NetworkInfo.dir/build
.PHONY : NetworkInfo/fast

#=============================================================================
# Target rules for targets named testsCPUUSAGE

# Build rule for target.
testsCPUUSAGE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testsCPUUSAGE
.PHONY : testsCPUUSAGE

# fast build rule for target.
testsCPUUSAGE/fast:
	$(MAKE) -f CMakeFiles/testsCPUUSAGE.dir/build.make CMakeFiles/testsCPUUSAGE.dir/build
.PHONY : testsCPUUSAGE/fast

#=============================================================================
# Target rules for targets named testsFLY

# Build rule for target.
testsFLY: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testsFLY
.PHONY : testsFLY

# fast build rule for target.
testsFLY/fast:
	$(MAKE) -f CMakeFiles/testsFLY.dir/build.make CMakeFiles/testsFLY.dir/build
.PHONY : testsFLY/fast

#=============================================================================
# Target rules for targets named testsCPU

# Build rule for target.
testsCPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testsCPU
.PHONY : testsCPU

# fast build rule for target.
testsCPU/fast:
	$(MAKE) -f CMakeFiles/testsCPU.dir/build.make CMakeFiles/testsCPU.dir/build
.PHONY : testsCPU/fast

#=============================================================================
# Target rules for targets named Example

# Build rule for target.
Example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Example
.PHONY : Example

# fast build rule for target.
Example/fast:
	$(MAKE) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/build
.PHONY : Example/fast

#=============================================================================
# Target rules for targets named CpuUsageModule

# Build rule for target.
CpuUsageModule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CpuUsageModule
.PHONY : CpuUsageModule

# fast build rule for target.
CpuUsageModule/fast:
	$(MAKE) -f CMakeFiles/CpuUsageModule.dir/build.make CMakeFiles/CpuUsageModule.dir/build
.PHONY : CpuUsageModule/fast

#=============================================================================
# Target rules for targets named CpuInfo

# Build rule for target.
CpuInfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CpuInfo
.PHONY : CpuInfo

# fast build rule for target.
CpuInfo/fast:
	$(MAKE) -f CMakeFiles/CpuInfo.dir/build.make CMakeFiles/CpuInfo.dir/build
.PHONY : CpuInfo/fast

#=============================================================================
# Target rules for targets named FlyModule

# Build rule for target.
FlyModule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FlyModule
.PHONY : FlyModule

# fast build rule for target.
FlyModule/fast:
	$(MAKE) -f CMakeFiles/FlyModule.dir/build.make CMakeFiles/FlyModule.dir/build
.PHONY : FlyModule/fast

#=============================================================================
# Target rules for targets named CpuFreqProcessesModule

# Build rule for target.
CpuFreqProcessesModule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CpuFreqProcessesModule
.PHONY : CpuFreqProcessesModule

# fast build rule for target.
CpuFreqProcessesModule/fast:
	$(MAKE) -f CMakeFiles/CpuFreqProcessesModule.dir/build.make CMakeFiles/CpuFreqProcessesModule.dir/build
.PHONY : CpuFreqProcessesModule/fast

core/Core.o: core/Core.cpp.o

.PHONY : core/Core.o

# target to build an object file
core/Core.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/core/Core.cpp.o
.PHONY : core/Core.cpp.o

core/Core.i: core/Core.cpp.i

.PHONY : core/Core.i

# target to preprocess a source file
core/Core.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/core/Core.cpp.i
.PHONY : core/Core.cpp.i

core/Core.s: core/Core.cpp.s

.PHONY : core/Core.s

# target to generate assembly for a file
core/Core.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/core/Core.cpp.s
.PHONY : core/Core.cpp.s

displays/NcursesDisplay.o: displays/NcursesDisplay.cpp.o

.PHONY : displays/NcursesDisplay.o

# target to build an object file
displays/NcursesDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/displays/NcursesDisplay.cpp.o
.PHONY : displays/NcursesDisplay.cpp.o

displays/NcursesDisplay.i: displays/NcursesDisplay.cpp.i

.PHONY : displays/NcursesDisplay.i

# target to preprocess a source file
displays/NcursesDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/displays/NcursesDisplay.cpp.i
.PHONY : displays/NcursesDisplay.cpp.i

displays/NcursesDisplay.s: displays/NcursesDisplay.cpp.s

.PHONY : displays/NcursesDisplay.s

# target to generate assembly for a file
displays/NcursesDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/displays/NcursesDisplay.cpp.s
.PHONY : displays/NcursesDisplay.cpp.s

displays/NcursesWindow.o: displays/NcursesWindow.cpp.o

.PHONY : displays/NcursesWindow.o

# target to build an object file
displays/NcursesWindow.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/displays/NcursesWindow.cpp.o
.PHONY : displays/NcursesWindow.cpp.o

displays/NcursesWindow.i: displays/NcursesWindow.cpp.i

.PHONY : displays/NcursesWindow.i

# target to preprocess a source file
displays/NcursesWindow.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/displays/NcursesWindow.cpp.i
.PHONY : displays/NcursesWindow.cpp.i

displays/NcursesWindow.s: displays/NcursesWindow.cpp.s

.PHONY : displays/NcursesWindow.s

# target to generate assembly for a file
displays/NcursesWindow.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/displays/NcursesWindow.cpp.s
.PHONY : displays/NcursesWindow.cpp.s

displays/SfmlDisplay.o: displays/SfmlDisplay.cpp.o

.PHONY : displays/SfmlDisplay.o

# target to build an object file
displays/SfmlDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/displays/SfmlDisplay.cpp.o
.PHONY : displays/SfmlDisplay.cpp.o

displays/SfmlDisplay.i: displays/SfmlDisplay.cpp.i

.PHONY : displays/SfmlDisplay.i

# target to preprocess a source file
displays/SfmlDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/displays/SfmlDisplay.cpp.i
.PHONY : displays/SfmlDisplay.cpp.i

displays/SfmlDisplay.s: displays/SfmlDisplay.cpp.s

.PHONY : displays/SfmlDisplay.s

# target to generate assembly for a file
displays/SfmlDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/displays/SfmlDisplay.cpp.s
.PHONY : displays/SfmlDisplay.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/main.cpp.s
.PHONY : main.cpp.s

src_sensor/CpuInfo.o: src_sensor/CpuInfo.cpp.o

.PHONY : src_sensor/CpuInfo.o

# target to build an object file
src_sensor/CpuInfo.cpp.o:
	$(MAKE) -f CMakeFiles/testsCPU.dir/build.make CMakeFiles/testsCPU.dir/src_sensor/CpuInfo.cpp.o
	$(MAKE) -f CMakeFiles/CpuInfo.dir/build.make CMakeFiles/CpuInfo.dir/src_sensor/CpuInfo.cpp.o
.PHONY : src_sensor/CpuInfo.cpp.o

src_sensor/CpuInfo.i: src_sensor/CpuInfo.cpp.i

.PHONY : src_sensor/CpuInfo.i

# target to preprocess a source file
src_sensor/CpuInfo.cpp.i:
	$(MAKE) -f CMakeFiles/testsCPU.dir/build.make CMakeFiles/testsCPU.dir/src_sensor/CpuInfo.cpp.i
	$(MAKE) -f CMakeFiles/CpuInfo.dir/build.make CMakeFiles/CpuInfo.dir/src_sensor/CpuInfo.cpp.i
.PHONY : src_sensor/CpuInfo.cpp.i

src_sensor/CpuInfo.s: src_sensor/CpuInfo.cpp.s

.PHONY : src_sensor/CpuInfo.s

# target to generate assembly for a file
src_sensor/CpuInfo.cpp.s:
	$(MAKE) -f CMakeFiles/testsCPU.dir/build.make CMakeFiles/testsCPU.dir/src_sensor/CpuInfo.cpp.s
	$(MAKE) -f CMakeFiles/CpuInfo.dir/build.make CMakeFiles/CpuInfo.dir/src_sensor/CpuInfo.cpp.s
.PHONY : src_sensor/CpuInfo.cpp.s

src_sensor/CpuUsage.o: src_sensor/CpuUsage.cpp.o

.PHONY : src_sensor/CpuUsage.o

# target to build an object file
src_sensor/CpuUsage.cpp.o:
	$(MAKE) -f CMakeFiles/testsCPUUSAGE.dir/build.make CMakeFiles/testsCPUUSAGE.dir/src_sensor/CpuUsage.cpp.o
	$(MAKE) -f CMakeFiles/CpuUsageModule.dir/build.make CMakeFiles/CpuUsageModule.dir/src_sensor/CpuUsage.cpp.o
.PHONY : src_sensor/CpuUsage.cpp.o

src_sensor/CpuUsage.i: src_sensor/CpuUsage.cpp.i

.PHONY : src_sensor/CpuUsage.i

# target to preprocess a source file
src_sensor/CpuUsage.cpp.i:
	$(MAKE) -f CMakeFiles/testsCPUUSAGE.dir/build.make CMakeFiles/testsCPUUSAGE.dir/src_sensor/CpuUsage.cpp.i
	$(MAKE) -f CMakeFiles/CpuUsageModule.dir/build.make CMakeFiles/CpuUsageModule.dir/src_sensor/CpuUsage.cpp.i
.PHONY : src_sensor/CpuUsage.cpp.i

src_sensor/CpuUsage.s: src_sensor/CpuUsage.cpp.s

.PHONY : src_sensor/CpuUsage.s

# target to generate assembly for a file
src_sensor/CpuUsage.cpp.s:
	$(MAKE) -f CMakeFiles/testsCPUUSAGE.dir/build.make CMakeFiles/testsCPUUSAGE.dir/src_sensor/CpuUsage.cpp.s
	$(MAKE) -f CMakeFiles/CpuUsageModule.dir/build.make CMakeFiles/CpuUsageModule.dir/src_sensor/CpuUsage.cpp.s
.PHONY : src_sensor/CpuUsage.cpp.s

src_sensor/DateModule.o: src_sensor/DateModule.cpp.o

.PHONY : src_sensor/DateModule.o

# target to build an object file
src_sensor/DateModule.cpp.o:
	$(MAKE) -f CMakeFiles/testsDate.dir/build.make CMakeFiles/testsDate.dir/src_sensor/DateModule.cpp.o
.PHONY : src_sensor/DateModule.cpp.o

src_sensor/DateModule.i: src_sensor/DateModule.cpp.i

.PHONY : src_sensor/DateModule.i

# target to preprocess a source file
src_sensor/DateModule.cpp.i:
	$(MAKE) -f CMakeFiles/testsDate.dir/build.make CMakeFiles/testsDate.dir/src_sensor/DateModule.cpp.i
.PHONY : src_sensor/DateModule.cpp.i

src_sensor/DateModule.s: src_sensor/DateModule.cpp.s

.PHONY : src_sensor/DateModule.s

# target to generate assembly for a file
src_sensor/DateModule.cpp.s:
	$(MAKE) -f CMakeFiles/testsDate.dir/build.make CMakeFiles/testsDate.dir/src_sensor/DateModule.cpp.s
.PHONY : src_sensor/DateModule.cpp.s

src_sensor/EntropyModule.o: src_sensor/EntropyModule.cpp.o

.PHONY : src_sensor/EntropyModule.o

# target to build an object file
src_sensor/EntropyModule.cpp.o:
	$(MAKE) -f CMakeFiles/EntropyInfo.dir/build.make CMakeFiles/EntropyInfo.dir/src_sensor/EntropyModule.cpp.o
.PHONY : src_sensor/EntropyModule.cpp.o

src_sensor/EntropyModule.i: src_sensor/EntropyModule.cpp.i

.PHONY : src_sensor/EntropyModule.i

# target to preprocess a source file
src_sensor/EntropyModule.cpp.i:
	$(MAKE) -f CMakeFiles/EntropyInfo.dir/build.make CMakeFiles/EntropyInfo.dir/src_sensor/EntropyModule.cpp.i
.PHONY : src_sensor/EntropyModule.cpp.i

src_sensor/EntropyModule.s: src_sensor/EntropyModule.cpp.s

.PHONY : src_sensor/EntropyModule.s

# target to generate assembly for a file
src_sensor/EntropyModule.cpp.s:
	$(MAKE) -f CMakeFiles/EntropyInfo.dir/build.make CMakeFiles/EntropyInfo.dir/src_sensor/EntropyModule.cpp.s
.PHONY : src_sensor/EntropyModule.cpp.s

src_sensor/Example.o: src_sensor/Example.cpp.o

.PHONY : src_sensor/Example.o

# target to build an object file
src_sensor/Example.cpp.o:
	$(MAKE) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src_sensor/Example.cpp.o
.PHONY : src_sensor/Example.cpp.o

src_sensor/Example.i: src_sensor/Example.cpp.i

.PHONY : src_sensor/Example.i

# target to preprocess a source file
src_sensor/Example.cpp.i:
	$(MAKE) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src_sensor/Example.cpp.i
.PHONY : src_sensor/Example.cpp.i

src_sensor/Example.s: src_sensor/Example.cpp.s

.PHONY : src_sensor/Example.s

# target to generate assembly for a file
src_sensor/Example.cpp.s:
	$(MAKE) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src_sensor/Example.cpp.s
.PHONY : src_sensor/Example.cpp.s

src_sensor/FlyModule.o: src_sensor/FlyModule.cpp.o

.PHONY : src_sensor/FlyModule.o

# target to build an object file
src_sensor/FlyModule.cpp.o:
	$(MAKE) -f CMakeFiles/testsFLY.dir/build.make CMakeFiles/testsFLY.dir/src_sensor/FlyModule.cpp.o
	$(MAKE) -f CMakeFiles/FlyModule.dir/build.make CMakeFiles/FlyModule.dir/src_sensor/FlyModule.cpp.o
.PHONY : src_sensor/FlyModule.cpp.o

src_sensor/FlyModule.i: src_sensor/FlyModule.cpp.i

.PHONY : src_sensor/FlyModule.i

# target to preprocess a source file
src_sensor/FlyModule.cpp.i:
	$(MAKE) -f CMakeFiles/testsFLY.dir/build.make CMakeFiles/testsFLY.dir/src_sensor/FlyModule.cpp.i
	$(MAKE) -f CMakeFiles/FlyModule.dir/build.make CMakeFiles/FlyModule.dir/src_sensor/FlyModule.cpp.i
.PHONY : src_sensor/FlyModule.cpp.i

src_sensor/FlyModule.s: src_sensor/FlyModule.cpp.s

.PHONY : src_sensor/FlyModule.s

# target to generate assembly for a file
src_sensor/FlyModule.cpp.s:
	$(MAKE) -f CMakeFiles/testsFLY.dir/build.make CMakeFiles/testsFLY.dir/src_sensor/FlyModule.cpp.s
	$(MAKE) -f CMakeFiles/FlyModule.dir/build.make CMakeFiles/FlyModule.dir/src_sensor/FlyModule.cpp.s
.PHONY : src_sensor/FlyModule.cpp.s

src_sensor/FrequencyPourcentage.o: src_sensor/FrequencyPourcentage.cpp.o

.PHONY : src_sensor/FrequencyPourcentage.o

# target to build an object file
src_sensor/FrequencyPourcentage.cpp.o:
	$(MAKE) -f CMakeFiles/testsCPU_FREQ.dir/build.make CMakeFiles/testsCPU_FREQ.dir/src_sensor/FrequencyPourcentage.cpp.o
	$(MAKE) -f CMakeFiles/CpuFreqProcessesModule.dir/build.make CMakeFiles/CpuFreqProcessesModule.dir/src_sensor/FrequencyPourcentage.cpp.o
.PHONY : src_sensor/FrequencyPourcentage.cpp.o

src_sensor/FrequencyPourcentage.i: src_sensor/FrequencyPourcentage.cpp.i

.PHONY : src_sensor/FrequencyPourcentage.i

# target to preprocess a source file
src_sensor/FrequencyPourcentage.cpp.i:
	$(MAKE) -f CMakeFiles/testsCPU_FREQ.dir/build.make CMakeFiles/testsCPU_FREQ.dir/src_sensor/FrequencyPourcentage.cpp.i
	$(MAKE) -f CMakeFiles/CpuFreqProcessesModule.dir/build.make CMakeFiles/CpuFreqProcessesModule.dir/src_sensor/FrequencyPourcentage.cpp.i
.PHONY : src_sensor/FrequencyPourcentage.cpp.i

src_sensor/FrequencyPourcentage.s: src_sensor/FrequencyPourcentage.cpp.s

.PHONY : src_sensor/FrequencyPourcentage.s

# target to generate assembly for a file
src_sensor/FrequencyPourcentage.cpp.s:
	$(MAKE) -f CMakeFiles/testsCPU_FREQ.dir/build.make CMakeFiles/testsCPU_FREQ.dir/src_sensor/FrequencyPourcentage.cpp.s
	$(MAKE) -f CMakeFiles/CpuFreqProcessesModule.dir/build.make CMakeFiles/CpuFreqProcessesModule.dir/src_sensor/FrequencyPourcentage.cpp.s
.PHONY : src_sensor/FrequencyPourcentage.cpp.s

src_sensor/NetworkModule.o: src_sensor/NetworkModule.cpp.o

.PHONY : src_sensor/NetworkModule.o

# target to build an object file
src_sensor/NetworkModule.cpp.o:
	$(MAKE) -f CMakeFiles/testsNETWORK.dir/build.make CMakeFiles/testsNETWORK.dir/src_sensor/NetworkModule.cpp.o
	$(MAKE) -f CMakeFiles/NetworkInfo.dir/build.make CMakeFiles/NetworkInfo.dir/src_sensor/NetworkModule.cpp.o
.PHONY : src_sensor/NetworkModule.cpp.o

src_sensor/NetworkModule.i: src_sensor/NetworkModule.cpp.i

.PHONY : src_sensor/NetworkModule.i

# target to preprocess a source file
src_sensor/NetworkModule.cpp.i:
	$(MAKE) -f CMakeFiles/testsNETWORK.dir/build.make CMakeFiles/testsNETWORK.dir/src_sensor/NetworkModule.cpp.i
	$(MAKE) -f CMakeFiles/NetworkInfo.dir/build.make CMakeFiles/NetworkInfo.dir/src_sensor/NetworkModule.cpp.i
.PHONY : src_sensor/NetworkModule.cpp.i

src_sensor/NetworkModule.s: src_sensor/NetworkModule.cpp.s

.PHONY : src_sensor/NetworkModule.s

# target to generate assembly for a file
src_sensor/NetworkModule.cpp.s:
	$(MAKE) -f CMakeFiles/testsNETWORK.dir/build.make CMakeFiles/testsNETWORK.dir/src_sensor/NetworkModule.cpp.s
	$(MAKE) -f CMakeFiles/NetworkInfo.dir/build.make CMakeFiles/NetworkInfo.dir/src_sensor/NetworkModule.cpp.s
.PHONY : src_sensor/NetworkModule.cpp.s

src_sensor/SysinfoModule.o: src_sensor/SysinfoModule.cpp.o

.PHONY : src_sensor/SysinfoModule.o

# target to build an object file
src_sensor/SysinfoModule.cpp.o:
	$(MAKE) -f CMakeFiles/SysinfoModule.dir/build.make CMakeFiles/SysinfoModule.dir/src_sensor/SysinfoModule.cpp.o
.PHONY : src_sensor/SysinfoModule.cpp.o

src_sensor/SysinfoModule.i: src_sensor/SysinfoModule.cpp.i

.PHONY : src_sensor/SysinfoModule.i

# target to preprocess a source file
src_sensor/SysinfoModule.cpp.i:
	$(MAKE) -f CMakeFiles/SysinfoModule.dir/build.make CMakeFiles/SysinfoModule.dir/src_sensor/SysinfoModule.cpp.i
.PHONY : src_sensor/SysinfoModule.cpp.i

src_sensor/SysinfoModule.s: src_sensor/SysinfoModule.cpp.s

.PHONY : src_sensor/SysinfoModule.s

# target to generate assembly for a file
src_sensor/SysinfoModule.cpp.s:
	$(MAKE) -f CMakeFiles/SysinfoModule.dir/build.make CMakeFiles/SysinfoModule.dir/src_sensor/SysinfoModule.cpp.s
.PHONY : src_sensor/SysinfoModule.cpp.s

src_sensor/UserInfo.o: src_sensor/UserInfo.cpp.o

.PHONY : src_sensor/UserInfo.o

# target to build an object file
src_sensor/UserInfo.cpp.o:
	$(MAKE) -f CMakeFiles/testsOS.dir/build.make CMakeFiles/testsOS.dir/src_sensor/UserInfo.cpp.o
	$(MAKE) -f CMakeFiles/UserInfo.dir/build.make CMakeFiles/UserInfo.dir/src_sensor/UserInfo.cpp.o
.PHONY : src_sensor/UserInfo.cpp.o

src_sensor/UserInfo.i: src_sensor/UserInfo.cpp.i

.PHONY : src_sensor/UserInfo.i

# target to preprocess a source file
src_sensor/UserInfo.cpp.i:
	$(MAKE) -f CMakeFiles/testsOS.dir/build.make CMakeFiles/testsOS.dir/src_sensor/UserInfo.cpp.i
	$(MAKE) -f CMakeFiles/UserInfo.dir/build.make CMakeFiles/UserInfo.dir/src_sensor/UserInfo.cpp.i
.PHONY : src_sensor/UserInfo.cpp.i

src_sensor/UserInfo.s: src_sensor/UserInfo.cpp.s

.PHONY : src_sensor/UserInfo.s

# target to generate assembly for a file
src_sensor/UserInfo.cpp.s:
	$(MAKE) -f CMakeFiles/testsOS.dir/build.make CMakeFiles/testsOS.dir/src_sensor/UserInfo.cpp.s
	$(MAKE) -f CMakeFiles/UserInfo.dir/build.make CMakeFiles/UserInfo.dir/src_sensor/UserInfo.cpp.s
.PHONY : src_sensor/UserInfo.cpp.s

unit_test/testCpuInfoModule.o: unit_test/testCpuInfoModule.cpp.o

.PHONY : unit_test/testCpuInfoModule.o

# target to build an object file
unit_test/testCpuInfoModule.cpp.o:
	$(MAKE) -f CMakeFiles/testsCPU.dir/build.make CMakeFiles/testsCPU.dir/unit_test/testCpuInfoModule.cpp.o
.PHONY : unit_test/testCpuInfoModule.cpp.o

unit_test/testCpuInfoModule.i: unit_test/testCpuInfoModule.cpp.i

.PHONY : unit_test/testCpuInfoModule.i

# target to preprocess a source file
unit_test/testCpuInfoModule.cpp.i:
	$(MAKE) -f CMakeFiles/testsCPU.dir/build.make CMakeFiles/testsCPU.dir/unit_test/testCpuInfoModule.cpp.i
.PHONY : unit_test/testCpuInfoModule.cpp.i

unit_test/testCpuInfoModule.s: unit_test/testCpuInfoModule.cpp.s

.PHONY : unit_test/testCpuInfoModule.s

# target to generate assembly for a file
unit_test/testCpuInfoModule.cpp.s:
	$(MAKE) -f CMakeFiles/testsCPU.dir/build.make CMakeFiles/testsCPU.dir/unit_test/testCpuInfoModule.cpp.s
.PHONY : unit_test/testCpuInfoModule.cpp.s

unit_test/testCpuUsage.o: unit_test/testCpuUsage.cpp.o

.PHONY : unit_test/testCpuUsage.o

# target to build an object file
unit_test/testCpuUsage.cpp.o:
	$(MAKE) -f CMakeFiles/testsCPUUSAGE.dir/build.make CMakeFiles/testsCPUUSAGE.dir/unit_test/testCpuUsage.cpp.o
.PHONY : unit_test/testCpuUsage.cpp.o

unit_test/testCpuUsage.i: unit_test/testCpuUsage.cpp.i

.PHONY : unit_test/testCpuUsage.i

# target to preprocess a source file
unit_test/testCpuUsage.cpp.i:
	$(MAKE) -f CMakeFiles/testsCPUUSAGE.dir/build.make CMakeFiles/testsCPUUSAGE.dir/unit_test/testCpuUsage.cpp.i
.PHONY : unit_test/testCpuUsage.cpp.i

unit_test/testCpuUsage.s: unit_test/testCpuUsage.cpp.s

.PHONY : unit_test/testCpuUsage.s

# target to generate assembly for a file
unit_test/testCpuUsage.cpp.s:
	$(MAKE) -f CMakeFiles/testsCPUUSAGE.dir/build.make CMakeFiles/testsCPUUSAGE.dir/unit_test/testCpuUsage.cpp.s
.PHONY : unit_test/testCpuUsage.cpp.s

unit_test/testDateModule.o: unit_test/testDateModule.cpp.o

.PHONY : unit_test/testDateModule.o

# target to build an object file
unit_test/testDateModule.cpp.o:
	$(MAKE) -f CMakeFiles/testsDate.dir/build.make CMakeFiles/testsDate.dir/unit_test/testDateModule.cpp.o
.PHONY : unit_test/testDateModule.cpp.o

unit_test/testDateModule.i: unit_test/testDateModule.cpp.i

.PHONY : unit_test/testDateModule.i

# target to preprocess a source file
unit_test/testDateModule.cpp.i:
	$(MAKE) -f CMakeFiles/testsDate.dir/build.make CMakeFiles/testsDate.dir/unit_test/testDateModule.cpp.i
.PHONY : unit_test/testDateModule.cpp.i

unit_test/testDateModule.s: unit_test/testDateModule.cpp.s

.PHONY : unit_test/testDateModule.s

# target to generate assembly for a file
unit_test/testDateModule.cpp.s:
	$(MAKE) -f CMakeFiles/testsDate.dir/build.make CMakeFiles/testsDate.dir/unit_test/testDateModule.cpp.s
.PHONY : unit_test/testDateModule.cpp.s

unit_test/testFlyModule.o: unit_test/testFlyModule.cpp.o

.PHONY : unit_test/testFlyModule.o

# target to build an object file
unit_test/testFlyModule.cpp.o:
	$(MAKE) -f CMakeFiles/testsFLY.dir/build.make CMakeFiles/testsFLY.dir/unit_test/testFlyModule.cpp.o
.PHONY : unit_test/testFlyModule.cpp.o

unit_test/testFlyModule.i: unit_test/testFlyModule.cpp.i

.PHONY : unit_test/testFlyModule.i

# target to preprocess a source file
unit_test/testFlyModule.cpp.i:
	$(MAKE) -f CMakeFiles/testsFLY.dir/build.make CMakeFiles/testsFLY.dir/unit_test/testFlyModule.cpp.i
.PHONY : unit_test/testFlyModule.cpp.i

unit_test/testFlyModule.s: unit_test/testFlyModule.cpp.s

.PHONY : unit_test/testFlyModule.s

# target to generate assembly for a file
unit_test/testFlyModule.cpp.s:
	$(MAKE) -f CMakeFiles/testsFLY.dir/build.make CMakeFiles/testsFLY.dir/unit_test/testFlyModule.cpp.s
.PHONY : unit_test/testFlyModule.cpp.s

unit_test/testFreqPercent.o: unit_test/testFreqPercent.cpp.o

.PHONY : unit_test/testFreqPercent.o

# target to build an object file
unit_test/testFreqPercent.cpp.o:
	$(MAKE) -f CMakeFiles/testsCPU_FREQ.dir/build.make CMakeFiles/testsCPU_FREQ.dir/unit_test/testFreqPercent.cpp.o
.PHONY : unit_test/testFreqPercent.cpp.o

unit_test/testFreqPercent.i: unit_test/testFreqPercent.cpp.i

.PHONY : unit_test/testFreqPercent.i

# target to preprocess a source file
unit_test/testFreqPercent.cpp.i:
	$(MAKE) -f CMakeFiles/testsCPU_FREQ.dir/build.make CMakeFiles/testsCPU_FREQ.dir/unit_test/testFreqPercent.cpp.i
.PHONY : unit_test/testFreqPercent.cpp.i

unit_test/testFreqPercent.s: unit_test/testFreqPercent.cpp.s

.PHONY : unit_test/testFreqPercent.s

# target to generate assembly for a file
unit_test/testFreqPercent.cpp.s:
	$(MAKE) -f CMakeFiles/testsCPU_FREQ.dir/build.make CMakeFiles/testsCPU_FREQ.dir/unit_test/testFreqPercent.cpp.s
.PHONY : unit_test/testFreqPercent.cpp.s

unit_test/testNetworkModule.o: unit_test/testNetworkModule.cpp.o

.PHONY : unit_test/testNetworkModule.o

# target to build an object file
unit_test/testNetworkModule.cpp.o:
	$(MAKE) -f CMakeFiles/testsNETWORK.dir/build.make CMakeFiles/testsNETWORK.dir/unit_test/testNetworkModule.cpp.o
.PHONY : unit_test/testNetworkModule.cpp.o

unit_test/testNetworkModule.i: unit_test/testNetworkModule.cpp.i

.PHONY : unit_test/testNetworkModule.i

# target to preprocess a source file
unit_test/testNetworkModule.cpp.i:
	$(MAKE) -f CMakeFiles/testsNETWORK.dir/build.make CMakeFiles/testsNETWORK.dir/unit_test/testNetworkModule.cpp.i
.PHONY : unit_test/testNetworkModule.cpp.i

unit_test/testNetworkModule.s: unit_test/testNetworkModule.cpp.s

.PHONY : unit_test/testNetworkModule.s

# target to generate assembly for a file
unit_test/testNetworkModule.cpp.s:
	$(MAKE) -f CMakeFiles/testsNETWORK.dir/build.make CMakeFiles/testsNETWORK.dir/unit_test/testNetworkModule.cpp.s
.PHONY : unit_test/testNetworkModule.cpp.s

unit_test/testOsModule.o: unit_test/testOsModule.cpp.o

.PHONY : unit_test/testOsModule.o

# target to build an object file
unit_test/testOsModule.cpp.o:
	$(MAKE) -f CMakeFiles/testsOS.dir/build.make CMakeFiles/testsOS.dir/unit_test/testOsModule.cpp.o
.PHONY : unit_test/testOsModule.cpp.o

unit_test/testOsModule.i: unit_test/testOsModule.cpp.i

.PHONY : unit_test/testOsModule.i

# target to preprocess a source file
unit_test/testOsModule.cpp.i:
	$(MAKE) -f CMakeFiles/testsOS.dir/build.make CMakeFiles/testsOS.dir/unit_test/testOsModule.cpp.i
.PHONY : unit_test/testOsModule.cpp.i

unit_test/testOsModule.s: unit_test/testOsModule.cpp.s

.PHONY : unit_test/testOsModule.s

# target to generate assembly for a file
unit_test/testOsModule.cpp.s:
	$(MAKE) -f CMakeFiles/testsOS.dir/build.make CMakeFiles/testsOS.dir/unit_test/testOsModule.cpp.s
.PHONY : unit_test/testOsModule.cpp.s

utils/DirectoryStream.o: utils/DirectoryStream.cpp.o

.PHONY : utils/DirectoryStream.o

# target to build an object file
utils/DirectoryStream.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/utils/DirectoryStream.cpp.o
.PHONY : utils/DirectoryStream.cpp.o

utils/DirectoryStream.i: utils/DirectoryStream.cpp.i

.PHONY : utils/DirectoryStream.i

# target to preprocess a source file
utils/DirectoryStream.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/utils/DirectoryStream.cpp.i
.PHONY : utils/DirectoryStream.cpp.i

utils/DirectoryStream.s: utils/DirectoryStream.cpp.s

.PHONY : utils/DirectoryStream.s

# target to generate assembly for a file
utils/DirectoryStream.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/utils/DirectoryStream.cpp.s
.PHONY : utils/DirectoryStream.cpp.s

utils/DynamicLibrary.o: utils/DynamicLibrary.cpp.o

.PHONY : utils/DynamicLibrary.o

# target to build an object file
utils/DynamicLibrary.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/utils/DynamicLibrary.cpp.o
.PHONY : utils/DynamicLibrary.cpp.o

utils/DynamicLibrary.i: utils/DynamicLibrary.cpp.i

.PHONY : utils/DynamicLibrary.i

# target to preprocess a source file
utils/DynamicLibrary.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/utils/DynamicLibrary.cpp.i
.PHONY : utils/DynamicLibrary.cpp.i

utils/DynamicLibrary.s: utils/DynamicLibrary.cpp.s

.PHONY : utils/DynamicLibrary.s

# target to generate assembly for a file
utils/DynamicLibrary.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_gkrellm.dir/build.make CMakeFiles/cpp_gkrellm.dir/utils/DynamicLibrary.cpp.s
.PHONY : utils/DynamicLibrary.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... testsOS"
	@echo "... testsCPU_FREQ"
	@echo "... EntropyInfo"
	@echo "... SysinfoModule"
	@echo "... testsNETWORK"
	@echo "... cpp_gkrellm"
	@echo "... testsDate"
	@echo "... UserInfo"
	@echo "... NetworkInfo"
	@echo "... testsCPUUSAGE"
	@echo "... testsFLY"
	@echo "... testsCPU"
	@echo "... Example"
	@echo "... CpuUsageModule"
	@echo "... CpuInfo"
	@echo "... FlyModule"
	@echo "... CpuFreqProcessesModule"
	@echo "... core/Core.o"
	@echo "... core/Core.i"
	@echo "... core/Core.s"
	@echo "... displays/NcursesDisplay.o"
	@echo "... displays/NcursesDisplay.i"
	@echo "... displays/NcursesDisplay.s"
	@echo "... displays/NcursesWindow.o"
	@echo "... displays/NcursesWindow.i"
	@echo "... displays/NcursesWindow.s"
	@echo "... displays/SfmlDisplay.o"
	@echo "... displays/SfmlDisplay.i"
	@echo "... displays/SfmlDisplay.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src_sensor/CpuInfo.o"
	@echo "... src_sensor/CpuInfo.i"
	@echo "... src_sensor/CpuInfo.s"
	@echo "... src_sensor/CpuUsage.o"
	@echo "... src_sensor/CpuUsage.i"
	@echo "... src_sensor/CpuUsage.s"
	@echo "... src_sensor/DateModule.o"
	@echo "... src_sensor/DateModule.i"
	@echo "... src_sensor/DateModule.s"
	@echo "... src_sensor/EntropyModule.o"
	@echo "... src_sensor/EntropyModule.i"
	@echo "... src_sensor/EntropyModule.s"
	@echo "... src_sensor/Example.o"
	@echo "... src_sensor/Example.i"
	@echo "... src_sensor/Example.s"
	@echo "... src_sensor/FlyModule.o"
	@echo "... src_sensor/FlyModule.i"
	@echo "... src_sensor/FlyModule.s"
	@echo "... src_sensor/FrequencyPourcentage.o"
	@echo "... src_sensor/FrequencyPourcentage.i"
	@echo "... src_sensor/FrequencyPourcentage.s"
	@echo "... src_sensor/NetworkModule.o"
	@echo "... src_sensor/NetworkModule.i"
	@echo "... src_sensor/NetworkModule.s"
	@echo "... src_sensor/SysinfoModule.o"
	@echo "... src_sensor/SysinfoModule.i"
	@echo "... src_sensor/SysinfoModule.s"
	@echo "... src_sensor/UserInfo.o"
	@echo "... src_sensor/UserInfo.i"
	@echo "... src_sensor/UserInfo.s"
	@echo "... unit_test/testCpuInfoModule.o"
	@echo "... unit_test/testCpuInfoModule.i"
	@echo "... unit_test/testCpuInfoModule.s"
	@echo "... unit_test/testCpuUsage.o"
	@echo "... unit_test/testCpuUsage.i"
	@echo "... unit_test/testCpuUsage.s"
	@echo "... unit_test/testDateModule.o"
	@echo "... unit_test/testDateModule.i"
	@echo "... unit_test/testDateModule.s"
	@echo "... unit_test/testFlyModule.o"
	@echo "... unit_test/testFlyModule.i"
	@echo "... unit_test/testFlyModule.s"
	@echo "... unit_test/testFreqPercent.o"
	@echo "... unit_test/testFreqPercent.i"
	@echo "... unit_test/testFreqPercent.s"
	@echo "... unit_test/testNetworkModule.o"
	@echo "... unit_test/testNetworkModule.i"
	@echo "... unit_test/testNetworkModule.s"
	@echo "... unit_test/testOsModule.o"
	@echo "... unit_test/testOsModule.i"
	@echo "... unit_test/testOsModule.s"
	@echo "... utils/DirectoryStream.o"
	@echo "... utils/DirectoryStream.i"
	@echo "... utils/DirectoryStream.s"
	@echo "... utils/DynamicLibrary.o"
	@echo "... utils/DynamicLibrary.i"
	@echo "... utils/DynamicLibrary.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

